# redhat72.-by-python
THIS TOOL IS FOR ALL NON TECHNICAL USERS , WHO WANT TO USE REDHAT BUT DSEN'T KNOW MUCH ABOUT IT
, SO BY USING THIS TOOL WHICH IS CODED IN PYTHON WILL BE A GIFT FOR THEM.


LOGN ID- root
LOGIN PASS - redhat
